---
title: "第一次作业"
author: "Group 2"
date: "2019/11/12"
toc-title: "目录"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggpubr)
library(igraph)
library(extrafont)
```

# 空手道俱乐部

绘制空手道俱乐部的可视化图，展示网络的几种统计性质（度分布，集聚系数，介数）。

## 网络可视化

空手道俱乐部的可视化图如图\@ref(fig:visualize-network)。

```{r visualize-network, fig.height=6, fig.width=6, fig.cap="网络可视化"}
karate_edge_list <- read_tsv("datasets/空手道俱乐部.txt", col_names = FALSE) %>%
  as.matrix()
karate_net <- graph_from_edgelist(karate_edge_list, directed = FALSE)
plot(
  karate_net,
  layout = layout_with_kk,
  vertex.color = "black",
  vertex.size = 6,
  vertex.label.cex = 0.6,
  vertex.label.color = "white",
  edge.curved = 0
)
```

## 节点网络指标

空手道网络各节点的网络性质指标如表\@ref(tab:description)。

```{r description}
karate_desc <- tibble(
  结点编号 = V(karate_net),
  度 = degree(karate_net),
  集聚系数 = transitivity(karate_net, "local"),
  介数 = betweenness(karate_net)
)
knitr::kable(karate_desc, caption = "各结点的基本网络指标", digits = 2)
```

## 整体网络指标

空手道网络的度分布图如图\@ref(fig:degree-distribution)

```{r degree-distribution, fig.cap="空手道网络度分布"}
ggplot(karate_desc, aes(度)) +
  geom_histogram(fill = "lightblue") +
  # scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(y = "频度") +
  theme_pubclean(base_family = "SimHei", base_size = 12)
```

基本统计指标：

* 平均度$<k>$：`r mean(karate_desc$度)`
* 平均集聚系数$C$：`r mean(karate_desc$集聚系数)`

# 随机网络

我们选取了N为20、40、60的三种情况，并对三种情况分别生成平均度为0.5，1和5的ER随机网络。表\@ref(tab:config-ER)给出了ER随机网络配置情况。

```{r define-ER-generation}
generate_random_network <- function(n, p) {
  edge_list <- expand_grid(n1 = 1:n, n2 = 1:n) %>%
    filter(n1 < n2) %>%
    mutate(
      connected = map_lgl(
        n1,
        ~ if_else(
          runif(1) < p,
          TRUE, FALSE
        )
      )
    ) %>%
    filter(connected) %>%
    select(n1, n2) %>%
    as.matrix()
  graph_from_edgelist(edge_list, directed = FALSE)
}
```

```{r config-ER}
config_er <- expand_grid(
  tibble(
    graph_type = c("平均度：0.5", "平均度：1", "平均度：5"),
    mean_k = c(0.5, 1, 5)
  ),
  n = c(20, 40, 60)
) %>%
  mutate(p = mean_k / n)
config_er %>%
  select(n, p, mean_k) %>%
  knitr::kable(
    digits = 4,
    col.names = c("N", "p", "平均度"),
    caption = "ER随机网络类型配置"
  )
```

```{r generate-ER, cache=TRUE}
set.seed(20191112)
random_graphs <- tibble(
  graph_type = c("平均度：0.5", "平均度：1", "平均度：5"),
  # generate 100 random networks for each type
  mean_k = c(0.5, 1, 5),
  n = 20, p = mean_k / n
) %>%
  slice(rep(row_number(), 100)) %>%
  mutate(
    graph = map2(
      n, p, generate_random_network
    )
  )
```

```{r select-er-graph}
graphs_to_plot <- random_graphs %>%
  group_by(graph_type) %>%
  nest() %>%
  mutate(
    graph_sel = map(
      data,
      ~ sample_n(.x, 1)
    )
  ) %>%
  unnest(graph_sel) %>%
  ungroup() %>%
  select(-data)
```

```{r visual-1}
plot(
  graphs_to_plot$graph[[1]],
  layout = layout_in_circle,
  vertex.color = "black",
  vertex.size = 4,
  vertex.label = NA,
  edge.curved = 0
)
```

```{r visual-2}
plot(
  graphs_to_plot$graph[[2]],
  layout = layout_in_circle,
  vertex.color = "black",
  vertex.size = 4,
  vertex.label = NA,
  edge.curved = 0
)
```

```{r visual-3}
plot(
  graphs_to_plot$graph[[3]],
  layout = layout_in_circle,
  vertex.color = "black",
  vertex.size = 4,
  vertex.label = NA,
  edge.curved = 0
)
```

```{r degree-distribution-ER}
random_graphs %>%
  mutate(
    degree = map(graph, degree)
  ) %>%
  unnest(degree) %>%
  group_by(graph_type, n, p, degree) %>%
  count(name = "count") %>%
  mutate(n_degree = count / n) %>%
  ggplot(aes(degree, n_degree)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "度", y = "")
  facet_wrap(~ graph_type)
```

```{r clustering-coefficient}
random_graphs %>%
  mutate(
    clustering_coeffiecient = map_dbl(
      graph,
      ~ transitivity(.x, "global")
    )
  ) %>%
  group_by(graph_type, n, p) %>%
  summarise(clustering_coeffiecient = mean(clustering_coeffiecient)) %>%
  knitr::kable(digits = 2)
```

# WS模型

# 实证网络
